### ISSUE TITLE
Getting "Resource not accessible by integration" error when publishing release

### ISSUE THREAD

**Issue by pschimmel** [GeorgDangl/Nuke.GitHub#8]
Hi!
I'm struggeling for days to integrate Nuke into one of my projects. So I was excited when I found your nice extension.
For some reason, there is a problem while creating a new release.
I'm not sure if I'm doing something wrong and if the issue is even related to your extension. 

The error output is this:

  20:08:38 [ERR] Target CreateRelease has thrown an exception
  Octokit.ForbiddenException: Resource not accessible by integration
     at Octokit.Connection.HandleErrors(IResponse response) in /_/Octokit/Http/Connection.cs:line 720
     at Octokit.Connection.RunRequest(IRequest request, CancellationToken cancellationToken) in /_/Octokit/Http/Connection.cs:line 701
     at Octokit.Connection.Run[T](IRequest request, CancellationToken cancellationToken) in /_/Octokit/Http/Connection.cs:line 686
     at Octokit.ApiConnection.Post[T](Uri uri, Object data, String accepts, String contentType, CancellationToken cancellationToken) in /_/Octokit/Http/ApiConnection.cs:line 293
     at Nuke.GitHub.GitHubTasks.PublishRelease(Configure`1 configure)
     at Build.<get_CreateRelease>b__42_3() in D:\a\FlowReports\FlowReports\build\Build.cs:line 280
     at Nuke.Common.Execution.TargetDefinition.<>c__DisplayClass80_0.<Executes>b__0() in /_/source/Nuke.Build/Execution/TargetDefinition.cs:line 73
     at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_2(Action x) in /_/source/Nuke.Build/Execution/BuildExecutor.cs:line 119
     at System.Collections.Generic.List`1.ForEach(Action`1 action)
     at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode) in /_/source/Nuke.Build/Execution/BuildExecutor.cs:line 119
  {"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/releases/releases#create-a-release"}

If needed, I can attach my Build.cs class

**Comment by GeorgDangl** [comment]
Hey @pschimmel, thank you for the issue!

I don't think this is caused by the plugin, it looks like a permissions issue. You're providing an access token when you try to call the release, and that token probably doesn't have permissions to create a release.

Any chance you're running this from within GitHub Actions and you provide the default token? Because I think not all permissions are automatically present there.

You would have to take a look at the GitHub Actions docs, but we had something similar just recently in a project, and all we had to do was configuring some permissions in the yaml file for GitHub Actions:
![image](https://github.com/GeorgDangl/Nuke.GitHub/assets/10274404/33c008e1-b9c0-4192-8200-4aaee4070684)

**Comment by GeorgDangl** [comment]
I think this project also does GitHub releases from within GitHub Actions, and there are some permissions configured: https://github.com/GeorgDangl/Dangl.SchneidControl/blob/develop/.github/workflows/continuous.yml

**Comment by pschimmel** [comment]
Hi Georg,
Thank you very much for the help. This is indeed not related to the Plugin, so I will close the issue.
After giving proper write permissions, creating a release works fine. 
Stupid me, I actually had the same issue when trying to publish pre-release packages. But I forgot about that.
